# Grabcut

cv2.grabCut(image, mask, rectangle, backgroundModel, foregroundModel, iterationCount[, mode])


### Parameters:

**image**: 8-bit 3-channel input image.

**mask**: 8-bit input/output single channel mask. The mask is initialized by the function when the mode is set to **GC_INIT_WITH_RECT**. Your elements can have one of the following values:

        1. GC_BGD defines obvious background pixels.
        2. GC_FGD defines an obvious foreground pixel (object).
        3. GC_PR_BGD defines a possible background pixel.
        4. GC_PR_FGD defines a possible foreground pixel.
        
**rectangle**: is the region of interest that contains a segmented object. Pixels outside the ROI are marked as background. The parameter is only used when mode == GC_INIT_WITH_RECT.

**backgroundModel**: temporary array for the background model.

**foregroundModel**: temporary array for the foreground model.

**iterationCount**: Number of iterations the algorithm must do before returning the result. Note that the result can be refined with other calls with mode == GC_INIT_WITH_MASK or mode == GC_EVAL.

**mode**: defines the operating mode. It can be one of the following:

        1. GC_INIT_WITH_RECT: The function initializes the state and mask using the given rectangle. After that, it runs the algorithm's iterCount iterations.
        2. GC_INIT_WITH_MASK: The function initializes the state using the mask provided. Note that GC_INIT_WITH_RECT and GC_INIT_WITH_MASK can be combined. Then all pixels outside the ROI are automatically initialized with GC_BGD.
        3. GC_EVAL: The value means the algorithm should just resume.

In [2]:
#!Python3

import cv2
import numpy as np
import matplotlib.pyplot as plt

image = cv2.imread('image_Exemple_Grabcut.png')
image_to_show = np.copy(image)

# Estados iniciais do mouse
cropping = False
x_init, y_init, top_left_pt, bottom_right_pt, width, height = 0, 0, 0, 0, 0, 0

def mouse_callback(event, x, y, flags, param):
    global image_to_show, x_init, y_init, top_left_pt, bottom_right_pt, cropping, width, height

    if event == cv2.EVENT_LBUTTONDOWN:
        cropping = True
        x_init, y_init = x, y
        image_to_show = np.copy(image)
        print(f'Starting point in X {x_init}')
        print(f'Y starting point {y_init}')

    elif event == cv2.EVENT_MOUSEMOVE:
        if cropping == True:
            image_to_show = np.copy(image)
            cv2.rectangle(image_to_show, (x_init, y_init),
                          (x, y), (0, 255, 0), 1)

    elif event == cv2.EVENT_LBUTTONUP:
        cropping = False
        top_left_pt, bottom_right_pt = x, y
        print(f'top point {top_left_pt}')
        print(f'low point {bottom_right_pt}')

        pontos = [x_init, y_init, top_left_pt, bottom_right_pt]

        width, height = [abs((top_left_pt - x_init)), abs((bottom_right_pt - y_init))]

        print(pontos)
        print(width, height)


cv2.namedWindow('image')
cv2.setMouseCallback('image', mouse_callback)

while True:

    cv2.imshow('image', image_to_show)
    k = cv2.waitKey(1)

    if k == ord('c'):
        if y_init > bottom_right_pt:
            y_init, bottom_right_pt = bottom_right_pt, y_init
        if x_init > top_left_pt:
            x_init, top_left_pt = top_left_pt, x_init

        if bottom_right_pt - y_init > 1 and top_left_pt - x_init > 0:
            image = image[y_init:bottom_right_pt, x_init:top_left_pt]
            mask = np.zeros(image.shape[:2], np.uint8)
            bgd = np.zeros((1, 65), np.float64)
            fgd = np.zeros((1, 65), np.float64)
            rect = (1, 1, width, height)

            cv2.grabCut(image, mask, rect, bgd, fgd, 5, cv2.GC_INIT_WITH_RECT)
            mask2 = np.where((mask == 2)|(mask == 0), 0, 1).astype('uint8') 
            image = image * mask2[:, :, np.newaxis] 
            print(image)
            image_to_show = np.copy(image)

    if k == ord('s'):
        cv2.imwrite('test.jpg', image_to_show)

    if cv2.waitKey(1) == ord('q'):
        break

cv2.destroyAllWindows()





Ponto inicial em X 967
Ponto inicial em Y 348
Ponto superior 1153
Ponto inferior 528
[967, 348, 1153, 528]
186 180
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
